_recursive_: true
_target_: pytorch_lightning.Trainer
checkpoint_callback: true
gpus: 1
progress_bar_refresh_rate: 1
max_epochs: 200
min_epochs: 10
val_check_interval: 1.0
flush_logs_every_n_steps: 100
log_every_n_steps: 50
benchmark: false
deterministic: true
