defaults:
  - embedding: default
  - optimizer: adam
  - scheduler: plateau

_recursive_: False
_target_: ens_transformer.models.DirectNet
n_transformers: 1
output_channels: 1
loss_str: crps
learning_rate: ${learning_rate}

transformer:
  kernel_size: 5
  activation: torch.nn.ReLU