defaults:
  - embedding: default
  - optimizer: adam
  - scheduler: plateau
  - transformer: residual

_recursive_: False
_target_: ens_transformer.models.DirectNet
n_transformers: 1
output_channels: 1
loss_str: crps
learning_rate: ${learning_rate}
