defaults:
  - embedding: default

_recursive_: False
_target_: ens_transformer.models.DirectNet
n_transformers: 1
hidden_channels: 64
output_channels: 1
loss_str: crps
learning_rate: ${learning_rate}
